
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]  # TODO Add version bumping

# specific branch build
trigger:
  branches:
    include:
    - master
    - develop

jobs:
  - job: tests
    displayName: Tests

    workspace:
      clean: all

    pool:
      vmImage: ubuntu-latest

    strategy:
      matrix:
        py38:
          python.version: '3.8'
          tox.env: py38

        py39:
          python.version: '3.9'
          tox.env: py39

        py310:
          python.version: '3.10'
          tox.env: py310

    steps:

      - task: UsePythonVersion@0
        displayName: Get Python for Python tools.
        inputs:
          versionSpec: '$(python.version)'
          addToPath: false
        name: Python

      - script: $(Python.pythonLocation)/bin/pip install --upgrade tox
        displayName: Install Python-based tools.

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: Use Python $(python.version) for tests.

      - script: $(Python.pythonLocation)/bin/tox -e '$(tox.env)'
        displayName: run tox -e '$(tox.env)'
