
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

# specific branch build
trigger:
  branches:
    include:
    - master
    - develop

jobs:
  - job: tests
    displayName: Tests

    workspace:
      clean: all

    pool:
      vmImage: ubuntu-latest

    strategy:
      matrix:
        py310:
          python.version: '3.10'
          tox.env: py310

        py311:
          python.version: '3.11'
          tox.env: py311

        py312:
          python.version: '3.12'
          tox.env: py312

    steps:

      - task: UsePythonVersion@0
        displayName: Get Python for Python tools.
        inputs:
          versionSpec: '$(python.version)'
          addToPath: false
        name: Python

      - script: $(Python.pythonLocation)/bin/pip install poetry
        displayName: Install Python-based tools.

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: Use Python $(python.version) for tests.

      - script: $(Python.pythonLocation)/bin/poetry run pytest .'
        displayName: tests
